//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Site.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class adm_usuario
    {
        public long usr_id { get; set; }
        public string usr_usuario { get; set; }
        public string usr_password { get; set; }
        public string usr_nombre { get; set; }
        public System.DateTime usr_fecha_tran { get; set; }
        public int usr_usuario_tran { get; set; }
        public bool usr_eliminado { get; set; }
    }
}
